### ISSUE TITLE
✨ Feat: 환경변수 secret manager 연동

### ISSUE THREAD

**Issue by adorableco** [swm-standard/Phote_BE#31]
### ✨ 기능 설명

- AWS secret manager 를 연동하여 환경변수를 관리하고자 함

---

### 📌 To-Do

- [x] secret manager 연결
- [x] DB 관련 환경 변수 처리
- [ ] 프로퍼티 파일 관련 환경 변수 처리

---

### 🙌🏻 기타 참고 사항

x

---
