### ISSUE TITLE
✨ Feat: deleteQuestioninWorkbook

### ISSUE THREAD

**Issue by adorableco** [swm-standard/Phote_BE#39]
### ✨ 기능 설명

- 문제집 내의 문제를 삭제하는 (제외시키는) 기능

#### 🙏 예상 Response Body 🙏

<img width="500" alt="스크린샷 2024-07-09 오후 10 02 17" src="https://github.com/swm-standard/Phote_BE/assets/90397541/fc88dfa9-a582-4cee-a10c-3e807364aa03">

---

### 📌 To-Do

- [x] 문제집 내 문제 삭제 기능 구현
- [x] workbook 관련 에러 exception 처리
- [x] question 관련 에러 exception 처리
- [ ] test !

---

### 🙌🏻 기타 참고 사항

x

---
